# Generated by Django 5.1.1 on 2024-09-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Subject_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sydney_Participant', models.BooleanField(default=False)),
                ('Sydney_Percentile', models.FloatField()),
                ('Correct_Answer', models.IntegerField()),
                ('Correct_answer_percentage_per_class', models.FloatField()),
                ('Participant', models.BooleanField(default=False)),
                ('Student_score', models.FloatField()),
                ('Category_Id', models.IntegerField()),
                ('Year_level_name', models.CharField(max_length=100)),
                ('Correct_answer_id', models.IntegerField()),
                ('Answer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.answer')),
                ('Assessment_Area_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.assessmentarea')),
                ('Award_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.award')),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.class')),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.school')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.student')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoprac2.subject')),
            ],
        ),
    ]
