# Generated by Django 5.1.1 on 2024-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprac2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Correct_Answer',
            field=models.TextField(),
        ),
    ]
