# Generated by Django 5.1.1 on 2024-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprac2', '0002_alter_summary_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Correct_answer_id',
            field=models.TextField(),
        ),
    ]
